kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30001  # port "na nodzie" (kontener kind)
      hostPort: 80          # port na Twoim Linuxie
      protocol: TCP
- role: worker
- role: worker