apiVersion: v1
kind: Pod
metadata:
  name: mongo-with-liveness
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
      startupProbe:
        tcpSocket:
          port: 27017
        periodSeconds: 5
        failureThreshold: 12
      livenessProbe:
        tcpSocket:
          port: 27017
        periodSeconds: 10
        failureThreshold: 3
