apiVersion: v1
kind: Pod
metadata:
  name: mongo-with-readiness
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
      startupProbe:
        tcpSocket:
          port: 27017
        periodSeconds: 5
        failureThreshold: 12
      readinessProbe:
        tcpSocket:
          port: 27017
        periodSeconds: 5
        failureThreshold: 3
