apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: "web-port"
    containerPort: 80
    -name: "web-port"
    containerPort: 8081